/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.app;

import test.list.LinkedList;

import static test.utilities.StringUtils.join;
import static test.utilities.StringUtils.split;
import static test.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
